In [43]:
# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("temp_matrix (25).csv")
#check the data types
data.dtypes

timestamp        int64
date            object
time            object
day             object
irradiance     float64
temperature    float64
00             float64
01             float64
02             float64
03             float64
04             float64
05             float64
06             float64
07             float64
08             float64
09             float64
10             float64
11             float64
12             float64
13             float64
14             float64
15             float64
16             float64
17             float64
18             float64
19             float64
20             float64
21             float64
22             float64
23             float64
24             float64
25             float64
26             float64
27             float64
28             float64
29             float64
30             float64
31             float64
pmax           float64
SCC              int64
panel           object
dtype: object

In [19]:
#clean data:
#clean = data[data.panel=='clean']

#dusty data:
#dusty = data[data.panel=='dusty']

#seperating data into frames:

#These are columns that don't need to be normalized
data1 = data[['timestamp','date','time','day','panel']]

#everything else minus the timestamp column does need to be normalized
data2 = data.select_dtypes(include = ['float64','int64'])
data2 = data2.drop(columns=['timestamp'])

In [20]:
#these columns are broken sensors, need to be replaced with 0's:
#01,02,04,07,12,15,16,19,24,27,29,30
data2.update(data2[['01','02','04','07','12','15','16','19','24','27','29','30']].fillna(0))

In [21]:
#replacing the remainder NaN with 
#by default this will be a linear interpolation unless a different method is specified
#(see interpolate documentation for other methods)
new_data2 = data2.interpolate()

In [30]:
#concatinating the dataframes:
df = pd.concat([data1, new_data2], axis=1)
df

,timestamp,date,time,day,panel,irradiance,temperature,00,01,02,...,24,25,26,27,28,29,30,31,pmax,SCC
0,1555390800,2019-04-16,9:01:06 AM,Tuesday,clean,557.80,28.21,31.4630,0.0,0.0,...,0.0,26.0680,25.9360,0.0,26.6240,0.0,0.0,25.9125,8801.920,673
1,1555390800,2019-04-16,9:01:06 AM,Tuesday,dusty,557.80,28.21,27.7050,0.0,0.0,...,0.0,25.6480,25.8800,0.0,20.5490,0.0,0.0,25.9610,7964.932,630
2,1555394400,2019-04-16,10:01:16 AM,Tuesday,clean,787.00,33.99,45.5560,0.0,0.0,...,0.0,46.5070,47.6900,0.0,44.8900,0.0,0.0,47.0325,56452.320,4520
3,1555394400,2019-04-16,10:01:16 AM,Tuesday,dusty,787.00,33.99,46.6650,0.0,0.0,...,0.0,47.3960,48.3070,0.0,0.0000,0.0,0.0,45.7140,40853.528,4447
4,1555398000,2019-04-16,11:01:52 AM,Tuesday,clean,916.77,32.31,49.9210,0.0,0.0,...,0.0,51.5880,53.0250,0.0,49.3400,0.0,0.0,52.6700,61858.730,5299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,1567342800,2019-09-01,5:06:48 PM,Sunday,dusty,3.14,38.30,44.1390,0.0,0.0,...,0.0,43.3630,43.5190,0.0,0.0000,0.0,0.0,42.3010,7421.639,792
3016,1567346400,2019-09-01,6:07:32 PM,Sunday,clean,3.14,38.30,41.3485,0.0,0.0,...,0.0,40.7325,40.9625,0.0,18.9850,0.0,0.0,40.1580,1429.268,224
3017,1567346400,2019-09-01,6:07:32 PM,Sunday,dusty,3.14,38.30,38.5580,0.0,0.0,...,0.0,38.1020,38.4060,0.0,37.9700,0.0,0.0,38.0150,671.760,140
3018,1567350000,2019-09-01,7:08:16 PM,Sunday,clean,3.14,38.30,36.9515,0.0,0.0,...,0.0,36.5910,36.7505,0.0,36.6875,0.0,0.0,36.6725,0.000,1
3019,1567350000,2019-09-01,7:08:16 PM,Sunday,dusty,3.14,38.30,35.3450,0.0,0.0,...,0.0,35.0800,35.0950,0.0,35.4050,0.0,0.0,35.3300,0.000,1

In [38]:
#seperating the newly revised data into frames for the independent & dependent variables
#the colon indicates all rows, and 'timestamp':'31' indicates all the columns from timestamp to 31

independent = df.loc[:,'irradiance':'31']
dependent = df.loc[:,'pmax':'SCC']

In [39]:
#not sure what the test size should be
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test,=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [50]:
#Feature Scaling the data:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_train

array([[ 1.31687346,  0.57019822,  0.6080381 , ...,  0.        ,
         0.        ,  0.91678783],
       [ 0.27394501,  0.73200524,  0.53009723, ...,  0.        ,
         0.        ,  0.49076067],
       [-1.26601397, -0.44936001,  1.68773197, ...,  0.        ,
         0.        ,  1.23931221],
       ...,
       [-0.85047237,  0.02910161, -0.58924936, ...,  0.        ,
         0.        , -0.54815728],
       [ 1.12944894,  1.61585435,  0.43762772, ...,  0.        ,
         0.        , -2.25000745],
       [-1.26601397, -0.31191104, -0.72907739, ...,  0.        ,
         0.        , -0.65943338]])

In [51]:
X_test = sc.transform(X_test)
X_test

array([[-1.14108159, -0.72077824, -0.9368127 , ...,  0.        ,
         0.        , -0.88208927],
       [ 0.58627596, -0.84082862,  0.11567009, ...,  0.        ,
         0.        ,  0.18471397],
       [-0.96183191,  0.23614501, -0.32789458, ...,  0.        ,
         0.        , -0.29096743],
       ...,
       [ 1.36031692, -1.51067489,  0.06606405, ...,  0.        ,
         0.        ,  0.23790341],
       [-0.62505429,  0.10565547, -0.0614026 , ...,  0.        ,
         0.        , -0.12661482],
       [ 0.19245608,  0.31269887,  0.30735167, ...,  0.        ,
         0.        ,  0.08087932]])

In [52]:
y_train = sc.fit_transform(y_train)
y_train

array([[ 1.15638098,  1.08590662],
       [ 0.234155  , -0.12387883],
       [ 0.07374432,  0.60177288],
       ...,
       [-1.24300844, -1.29249645],
       [-0.13277511,  0.31524474],
       [-1.51188217, -1.54663922]])

In [53]:
y_test = sc.fit_transform(y_test)
y_test

array([[-1.38742555, -1.36593133],
       [ 1.20968642,  0.67295249],
       [-1.28740733, -1.28253703],
       ...,
       [ 2.0173692 ,  1.57959826],
       [-0.9341388 , -0.93292245],
       [-0.59539366, -0.42560709]])